export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const ADMIN_ALL_USERS_REQUEST = "ADMIN_ALL_USERS_REQUEST";
export const ADMIN_ALL_USERS_SUCCESS = "ADMIN_ALL_USERS_SUCCESS";
export const ADMIN_ALL_USERS_FAIL = "ADMIN_ALL_USERS_FAIL";

export const ADMIN_SINGLE_USER_REQUEST = "ADMIN_SINGLE_USER_REQUEST";
export const ADMIN_SINGLE_USER_SUCCESS = "ADMIN_SINGLE_USER_SUCCESS";
export const ADMIN_SINGLE_USER_FAIL = "ADMIN_SINGLE_USER_FAIL";

export const ADMIN_UPDATE_PROFILE_REQUEST = "ADMIN_UPDATE_PROFILE_REQUEST";
export const ADMIN_UPDATE_PROFILE_SUCCESS = "ADMIN_UPDATE_PROFILE_SUCCESS";
export const ADMIN_UPDATE_PROFILE_FAIL = "ADMIN_UPDATE_PROFILE_FAIL";
export const ADMIN_UPDATE_PROFILE_RESET = "ADMIN_UPDATE_PROFILE_RESET";

export const ADMIN_DELETE_PROFILE_REQUEST = "ADMIN_DELETE_PROFILE_REQUEST";
export const ADMIN_DELETE_PROFILE_SUCCESS = "ADMIN_DELETE_PROFILE_SUCCESS";
export const ADMIN_DELETE_PROFILE_FAIL = "ADMIN_DELETE_PROFILE_FAIL";
export const ADMIN_DELETE_PROFILE_RESET = "ADMIN_DELETE_PROFILE_RESET";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFLE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFLE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFLE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFLE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";

export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
